Description of setcon_cmm3
setcon_cmm3
PURPOSE
setcon_cmm3: Assembels the contraint matrix
SYNOPSIS
function [Ab,blc,buc,bs,bt,subi] = setcon_cmm3(nel,G,options)
DESCRIPTION
 setcon_cmm3: Assembels the contraint matrix
  FORMAT: [Ab,blc,buc,bs,bt,subi] = setcon_cmm3(nel,G,varargin)
 Input:
  nel: Number of elements
  G: struct: material struct used in program
   Concrete (reinforced)
    G.type{i} = 'RC' OR 'RC2';
    G.mat{i} =  [fc ft k Ax fYx Ay fYy Az fYz];
    G.A(:,i) = [G.mat{i}(4) G.mat{i}(6) G.mat{i}(8)];
   Steel
    G.type{i} = 'S';
    G.mat{i} = fY;
   (Modified) Mohr-coulomb - Concrete
    G.type{i} = 'MC' OR 'MMC' OR 'C2';
    G.mat{i} =  [fc ft k];
  options: struct: Struct containing values for optional parameters
 Output:
  Ab: Constrint matrix
  blc: Lower yield criteria
  buc: Upper yield criteria
  bs: Variable limits of steel
  bt: Variable limits of total stresses
  subi: subindexes for the equations of semidefinte conic constraints
 Latest author:
 30-07-2019 Mads Emil Møller Andersen - MEMAndersen@gmail.com
CROSS-REFERENCE INFORMATION
This function calls:
text_progress_bar This function creates a text progress bar. It should be called with a
Ab_MMC_ps3 Ab_MMC_ps3: Modified Mohr-Coulomb material point on 3D. Uses two
Ab_RC2_ps3 Ab_RC2_ps3: Mohr coulomb reinforced concrete yield condition in 3D using
Ab_RC_ps3 Ab_RC_ps3: Mohr coulomb reinforced concrete yield condition in 3D using
Ab_S_ps3 Ab_S_ps: Von Mises yield condition for steel in 3d triaxial stress using
This function is called by:
fela_main fela_main: Main runner of the FELA-program
SOURCE CODE
function [Ab,blc,buc,bs,bt,subi] = setcon_cmm3(nel,G,options)
% setcon_cmm3: Assembels the contraint matrix
%  FORMAT: [Ab,blc,buc,bs,bt,subi] = setcon_cmm3(nel,G,varargin)
%
%
% Input:
%  nel: Number of elements
%  G: struct: material struct used in program
%   Concrete (reinforced)
%
%    G.type{i} = 'RC' OR 'RC2';
%    G.mat{i} =  [fc ft k Ax fYx Ay fYy Az fYz];
%    G.A(:,i) = [G.mat{i}(4) G.mat{i}(6) G.mat{i}(8)];
%
%   Steel
%    G.type{i} = 'S';
%    G.mat{i} = fY;
%
%   (Modified) Mohr-coulomb - Concrete
%    G.type{i} = 'MC' OR 'MMC' OR 'C2';
%    G.mat{i} =  [fc ft k];
%
%  options: struct: Struct containing values for optional parameters
%
%
% Output:
%  Ab: Constrint matrix
%  blc: Lower yield criteria
%  buc: Upper yield criteria
%  bs: Variable limits of steel
%  bt: Variable limits of total stresses
%  subi: subindexes for the equations of semidefinte conic constraints
%
% Latest author:
% 30-07-2019 Mads Emil Møller Andersen - MEMAndersen@gmail.com
% Unpacking optional parameters
stressFac = options.setcon.fy_cap;
% Count members of each material
n.RC = sum(ismember(cellstr(G.type),'RC'));
n.S = sum(ismember(cellstr(G.type),'S'));
n.MC = sum(ismember(cellstr(G.type),'MC'));
n.RC2 = sum(ismember(cellstr(G.type),'RC2'));
% Number of auxillirary parameters
% Number of extra parameters (stress and aux)
naM.RC = 4;
naM.S = 7;
naM.MC = 2;
naM.RC2 = 5;
% Total number of coupling equations
nrM.RC = 18;
nrM.S = 7;
nrM.MC = 14;
nrM.RC2 = 14;
% Number of eqn used for semidefinite vars
nr_subi_M.RC = 18;
nr_subi_M.S = -1; %(-1 used to not increment counter for steel)
nr_subi_M.MC = 12;
nr_subi_M.RC2 = 12;
% Preallocations for sparse indexing
aval = nrM.RC*naM.RC*n.RC + nrM.S*naM.S*n.S + nrM.MC*naM.MC*n.MC ...
    + nrM.RC2*naM.RC2*n.RC2;
bval = nrM.RC*n.RC + nrM.S*n.S + nrM.MC*n.MC + nrM.RC2*n.RC2;
a_array = cell(aval,1);
a_index = 1;
blc = zeros(bval,1);
buc = zeros(bval,1);
% Limits for smeared steel
bs = zeros(1,3*n.RC+3*n.RC2);
% Limits for total stress vars
bt = zeros(1,6*(n.RC+n.S+n.MC+n.RC2));
subi = zeros(1,18*n.RC+12*(n.MC+n.RC2));
subi_index = 0;
%% Row incremental counters (equations)
r1 = 0;
r2 = r1;
%% Column incremental counters (Auxiliary parameters)
c_t1 = 0; % Total stresses
c_t2 = c_t1;
c_lam = nel*6+1; % (lambda)
c_s1 = c_lam;  % Reinforcement stresses
c_s2 = c_s1;
c_alpha_RC = c_s1+3*(n.RC+n.RC2); % aux. vars. RC
c_alpha_S_1 = c_alpha_RC+n.RC; % aux. vars. S
c_alpha_S_2 = c_alpha_S_1;
c_alpha_MC_1 = c_alpha_S_1+7*n.S;
c_alpha_MC_2 = c_alpha_MC_1;
c_alpha_RC2_1 = c_alpha_MC_1+2*n.MC;
c_alpha_RC2_2 = c_alpha_RC2_1;
i_bs1 = 0; % Steel limits
i_bs2 = i_bs1;
%% Progessbar init
text_progress_bar(sprintf('%-20s', 'setcon'));
%% Main loop over elements
for el = 1:nel
    %progressbar update
    if any(el == [1,nel]) || mod(el,ceil(el/100)) == 0
        text_progress_bar(el/nel*100);
    end
    % Reinforced concrete init
    if strcmp(G.type{el},'RC')
        % Material parameters
        k = G.mat{el}(1); fc = G.mat{el}(2); ft = G.mat{el}(3);
        Asx = G.mat{el}(4); fYx = G.mat{el}(5);
        Asy = G.mat{el}(6); fYy = G.mat{el}(7);
        Asz = G.mat{el}(8); fYz = G.mat{el}(9);
        [A, bye, bs_e] = Ab_RC_ps3(k,fc,ft,Asx,fYx,Asy,fYy,Asz,fYz);
        % Concrete stress part
        Asig = A(:,1:6);
        % Steel and Aux part
        Ast = A(:,7:9);
        Aa = A(:,10);
        % Number of equations per element
        nr = nrM.RC;
        nr_subi = nr_subi_M.RC;
    % Steel init
    elseif strcmp(G.type{el},'S')
        % Material parameters
        fY = G.mat{el}(1);
        [Aseq, Aaeq, byeq] = Ab_S_ps3(fY);
        % Number of equations per element
        nr = nrM.S;
        nr_subi = nr_subi_M.S;
    % MC init
    elseif strcmp(G.type{el},'MC')
        % Material parameters
        k = G.mat{el}(1); fc = G.mat{el}(2); ft = G.mat{el}(3);
        [A, blc_e, buc_e] = Ab_MMC_ps3(k, fc, ft);
        % Concrete stress part
        Asig = A(:,1:6);
        % Aux part
        Aa = A(:,7:8);
        % Number of equations per element
        nr = nrM.MC;
        nr_subi = nr_subi_M.MC;
    %RC2 init
    elseif strcmp(G.type{el},'RC2')
        % Material parameters
        k = G.mat{el}(1); fc = G.mat{el}(2); ft = G.mat{el}(3);
        Asx = G.mat{el}(4); fYx = G.mat{el}(5);
        Asy = G.mat{el}(6); fYy = G.mat{el}(7);
        Asz = G.mat{el}(8); fYz = G.mat{el}(9);
        [A, blc_e, buc_e, bs_e] = Ab_RC2_ps3(k,fc,ft,Asx,fYx,Asy,fYy,Asz,fYz);
        % Concrete stress part
        Asig = A(:,1:6);
        % Steel and Aux part
        Ast = A(:,7:9);
        Aa = A(:,10:11);
        % Number of equations per element
        nr = nrM.RC2;
        % Number of subi equations
        nr_subi = nr_subi_M.RC2;
    end
    % ROW for element (equations)
    r1 = r2 + 1;
    r2 = r1+nr-1;
    r = r1:r2;
    % row for subi;
    r_subi = r1:r1+nr_subi-1;
    % col for total stress part
    c_t1 = c_t2+1;
    c_t2 = c_t1+5;
    % Reinforced concrete
    if strcmp(G.type{el},'RC')
        % Subindex for semidefinate cones
        subi(subi_index+1:subi_index+nr_subi) = r_subi;
        subi_index = subi_index + nr_subi;
        % Total stress part
        c = c_t1:c_t2;
        % Create
        r_rep = repmat(r,1,length(c))';
        c_rep = repelem(c,length(r))';
        Ab_rep=[Asig];
        for i = 1:(length(c)*length(r))
            a_array{a_index} = [r_rep(i) c_rep(i) Ab_rep(i)];
            a_index = a_index+1;
        end
        % Stress limits for total stress
        bt(c) = inf;
        % steel part
        c_s1 = c_s2+1;
        c_s2 = c_s1+2;
        c = c_s1:c_s2;
        % create steel
        r_rep = repmat(r,1,length(c))';
        c_rep = repelem(c,length(r))';
        Ab_rep=[Ast];
        for i = 1:(length(c)*length(r))
            a_array{a_index} = [r_rep(i) c_rep(i) Ab_rep(i)];
            a_index = a_index+1;
        end
        % alpha part
        c_alpha_RC = c_alpha_RC + 1;
        c=c_alpha_RC;
        % create alpha
        r_rep = repmat(r,1,length(c))';
        c_rep = repelem(c,length(r))';
        Ab_rep=[Aa];
        for i = 1:(length(c)*length(r))
            a_array{a_index} = [r_rep(i) c_rep(i) Ab_rep(i)];
            a_index = a_index+1;
        end
        % b part
        blc(r) = [-inf];
        buc(r) = [ bye];
        % steel limits
        i_bs1 = i_bs2 + 1;
        i_bs2 = i_bs1 + 2;
        bs(i_bs1:i_bs2) = bs_e;
        % Steel
    elseif strcmp(G.type{el},'S')
        % Total stress part
        c = c_t1:c_t2;
        % create total stress part
        r_rep = repmat(r,1,length(c))';
        c_rep = repelem(c,length(r))';
        Ab_rep=Aseq;
        for i = 1:(length(c)*length(r))
            a_array{a_index} = [r_rep(i) c_rep(i) Ab_rep(i)];
            a_index = a_index+1;
        end
        % Stress limits for total stress
        bt(c) = stressFac*fY;
        % alfa part
        c_alpha_S_1 = c_alpha_S_2 + 1;
        c_alpha_S_2 = c_alpha_S_1 + 6;
        c=c_alpha_S_1:c_alpha_S_2;
        r_rep = repmat(r,1,length(c))';
        c_rep = repelem(c,length(r))';
        % create alfa part
        Ab_rep=[Aaeq];
        for i = 1:(length(c)*length(r))
            a_array{a_index} = [r_rep(i) c_rep(i) Ab_rep(i)];
            a_index = a_index+1;
        end
        % b part
        blc(r) = byeq;
        buc(r) = byeq;
        % Mohr-coulomb
    elseif strcmp(G.type{el},'MC')
        % Subindex for semidefinate cones
        subi(subi_index+1:subi_index + nr_subi) = r_subi;
        subi_index = subi_index + nr_subi;
        % Total stress part
        c = c_t1:c_t2;
        % Create
        r_rep = repmat(r,1,length(c))';
        c_rep = repelem(c,length(r))';
        Ab_rep=[Asig];
        for i = 1:(length(c)*length(r))
            a_array{a_index} = [r_rep(i) c_rep(i) Ab_rep(i)];
            a_index = a_index+1;
        end
        % Stress limits for total stress
        bt(c) = inf;
        % alpha part
        c_alpha_MC_1 = c_alpha_MC_2 + 1;
        c_alpha_MC_2 = c_alpha_MC_1 + 1;
        c=c_alpha_MC_1:c_alpha_MC_2;
        % create alpha
        r_rep = repmat(r,1,length(c))';
        c_rep = repelem(c,length(r))';
        Ab_rep=[Aa];
        for i = 1:(length(c)*length(r))
            a_array{a_index} = [r_rep(i) c_rep(i) Ab_rep(i)];
            a_index = a_index+1;
        end
        % b part
        blc(r) = [blc_e];
        buc(r) = [buc_e];
    % Reinforced concrete 2
    elseif strcmp(G.type{el},'RC2')
        % Subindex for semidefinate cones
        subi(subi_index+1:subi_index + nr_subi) = r_subi;
        subi_index = subi_index + nr_subi;
        % Total stress part
        c = c_t1:c_t2;
        % Create
        r_rep = repmat(r,1,length(c))';
        c_rep = repelem(c,length(r))';
        Ab_rep=[Asig];
        for i = 1:(length(c)*length(r))
            a_array{a_index} = [r_rep(i) c_rep(i) Ab_rep(i)];
            a_index = a_index+1;
        end
        % Stress limits for total stress
        bt(c) = inf;
        % steel part
        c_s1 = c_s2+1;
        c_s2 = c_s1+2;
        c = c_s1:c_s2;
        % create steel
        r_rep = repmat(r,1,length(c))';
        c_rep = repelem(c,length(r))';
        Ab_rep=[Ast];
        for i = 1:(length(c)*length(r))
            a_array{a_index} = [r_rep(i) c_rep(i) Ab_rep(i)];
            a_index = a_index+1;
        end
        % alpha part
        c_alpha_MC_1 = c_alpha_MC_2 + 1;
        c_alpha_MC_2 = c_alpha_MC_1 + 1;
        c=c_alpha_MC_1:c_alpha_MC_2;
        % create alpha
        r_rep = repmat(r,1,length(c))';
        c_rep = repelem(c,length(r))';
        Ab_rep=[Aa];
        for i = 1:(length(c)*length(r))
            a_array{a_index} = [r_rep(i) c_rep(i) Ab_rep(i)];
            a_index = a_index+1;
        end
        % b part
        blc(r) = [blc_e];
        buc(r) = [buc_e];
        % steel limits
        i_bs1 = i_bs2 + 1;
        i_bs2 = i_bs1 + 2;
        bs(i_bs1:i_bs2) = bs_e;
    end
end
% End progressbar
text_progress_bar(sprintf('done in %8.2fs',toc));
% Generate sparse matrix
IJV = cell2mat(a_array);
Ab = sparse(IJV(:,1),IJV(:,2),IJV(:,3));
blc = sparse(blc);
buc = sparse(buc);
bs = sparse(bs);
bt = sparse(bt);