Description of seth_cmm3
seth_cmm3
PURPOSE
seth_cmm: Assembles the global equilibrium matrix
SYNOPSIS
function H=seth_cmm3(X,T,nel,neq,nvar,eqperel,varperel)
DESCRIPTION
 seth_cmm: Assembles the global equilibrium matrix
 prooperties of the mesh.
  FORMAT: H=seth_cmm(X,T,nel,neq,nvar,eqperel,varperel)
 Input:
  X: Node coordinate matrix [x, y z]
  T: Node toplogy matrix [n1, n2, n3, n4]
  nel: Number of elements
  neq: Number of equilibrium equations
  nvar: Number of stress variabels
  eqperel: Equations per element. Determines which variabels join
  varperel: Variabels per element. Dimensions nel x 6
 Output:
  H: Global equilibrium matrix
 16-02-2018 Mads Emil Møller Andersen & Nikolaj Skafte Koch
CROSS-REFERENCE INFORMATION
This function calls:
hplst_cmm3 hplst_cmm3: compute h(equilibrium matrix) for a triaxial tetrahedron
text_progress_bar This function creates a text progress bar. It should be called with a
This function is called by:
fela_main fela_main: Main runner of the FELA-program
SOURCE CODE
function H=seth_cmm3(X,T,nel,neq,nvar,eqperel,varperel)
% seth_cmm: Assembles the global equilibrium matrix
% prooperties of the mesh.
%  FORMAT: H=seth_cmm(X,T,nel,neq,nvar,eqperel,varperel)
% Input:
%  X: Node coordinate matrix [x, y z]
%  T: Node toplogy matrix [n1, n2, n3, n4]
%  nel: Number of elements
%  neq: Number of equilibrium equations
%  nvar: Number of stress variabels
%  eqperel: Equations per element. Determines which variabels join
%  varperel: Variabels per element. Dimensions nel x 6
% Output:
%  H: Global equilibrium matrix
% 16-02-2018 Mads Emil Møller Andersen & Nikolaj Skafte Koch
% Preallocates cellarray to store sparse definition
nval = 6*12*nel;
Cellarray = cell(nval,1);
% Loop over elements and compute local h
j = 1;
text_progress_bar(sprintf('%-20s', 'seth'));
for el=1:nel
    if any(el == [1,nel]) || mod(el,ceil(nel/100)) == 0
        text_progress_bar(el/nel*100);
    end
    h=hplst_cmm3(X(T(el,:),:),T(el,:));
    eqperelrep = repmat(eqperel(el,:),1,length(varperel(el,:)))';
    varperelrep = repelem(varperel(el,:),length(eqperel(el,:)))';
    for i = 1:(length(varperel(el,:))*length(eqperel(el,:)))
        Cellarray{j} = [eqperelrep(i) varperelrep(i) h(i)];
        j = j+1;
    end
end
text_progress_bar(sprintf('done in %8.2fs',toc));
% Assemble global H
IJV = cell2mat(Cellarray);
H = sparse(IJV(:,1),IJV(:,2),IJV(:,3),neq,nvar);