Description of text_progress_bar
text_progress_bar
PURPOSE
This function creates a text progress bar. It should be called with a
SYNOPSIS
function text_progress_bar(c)
DESCRIPTION
 This function creates a text progress bar. It should be called with a
 STRING argument to initialize and terminate. Otherwise the number correspoding
 to progress in % should be supplied.
 INPUTS:   C   Either: Text string to initialize or terminate
                       Percentage number to show progress
 OUTPUTS:  N/A
 Author: Paul Proteus (e-mail: proteus.paul (at) yahoo (dot) com)
 Version: 1.0
 Changes tracker:  29.06.2010  - First version
 Modified by Mads Emil Møller Andersen 13-06-2019
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
setcon_cmm3 rewriteL: Assembels the contraint matrix
seth_cmm3 seth_cmm: Assembles the global equilibrium matrix
setvareq_cmm3 setvareq_cmm: Sets variable equations and determines varous geometric
fela_init fela_init: Initialize mosek and set various settings related to logging
SOURCE CODE
function text_progress_bar(c)
% This function creates a text progress bar. It should be called with a
% STRING argument to initialize and terminate. Otherwise the number correspoding
% to progress in % should be supplied.
% INPUTS:   C   Either: Text string to initialize or terminate
%                       Percentage number to show progress
% OUTPUTS:  N/A
% Author: Paul Proteus (e-mail: proteus.paul (at) yahoo (dot) com)
% Version: 1.0
% Changes tracker:  29.06.2010  - First version
%
% Modified by Mads Emil Møller Andersen 13-06-2019
% Inspired by: http://blogs.mathworks.com/loren/2007/08/01/monitoring-progress-of-a-calculation/
%% Initialization
persistent strCR;           %   Carriage return pesistent variable
persistent cw_logging;           %   if toogle is false no output is shown
% Vizualization parameters
strPercentageLength = 10;   %   Length of percentage string (must be >5)
strDotsMaximum      = 10;   %   The total number of dots in a progress bar
% control logging to command window
if isempty(cw_logging) || strcmp(c, 'cw_logging_on')
    cw_logging = true;
    return
elseif strcmp(c, 'cw_logging_off')
    cw_logging = false;
    return
elseif strcmp(c, 'cw_logging')
    cw_logging = ~cw_logging;
    return
end
%% Main
if cw_logging
    if isempty(strCR) && ~ischar(c)
        % Progress bar must be initialized with a string
        error('The text progress must be initialized with a string');
    elseif isempty(strCR) && ischar(c)
        % Progress bar - initialization
        fprintf('%s',c);
        strCR = -1;
    elseif ~isempty(strCR) && ischar(c)
        % Progress bar  - termination
        strCR = [];
        fprintf([c '\n']);
    elseif isnumeric(c)
        % Progress bar - normal progress
        c = floor(c);
        percentageOut = [num2str(c) '%%'];
        percentageOut = [percentageOut repmat(' ',1,strPercentageLength-length(percentageOut)-1)];
        nDots = floor(c/100*strDotsMaximum);
        dotOut = ['[' repmat('.',1,nDots) repmat(' ',1,strDotsMaximum-nDots) ']'];
        strOut = [percentageOut dotOut];
        % Print it on the screen
        if strCR == -1
            % Don't do carriage return during first run
            fprintf(strOut);
        else
            % Do it during all the other runs
            fprintf([strCR strOut]);
        end
        % Update carriage return
        strCR = repmat('\b',1,length(strOut)-1);
    else
        % Any other unexpected input
        error('Unsupported argument type');
    end
end