Description of fela_main
fela_main
PURPOSE
fela_main: Main runner of the FELA-program
SYNOPSIS
function [sol, prob]= fela_main(msh_path, materials, supports, loads, varargin)
DESCRIPTION
 fela_main: Main runner of the FELA-program
  FORMAT: res = fela_main(msh_path, material, supports, loads, varargin)
 Input:
  msh_path: string: Path to mesh file, by default this is expected to be a
   .msh file v. 4.1 created in GMSH
  materials: struct: struct with the following build:
   materials.(material_name).type = (str), where str is either:
   'S' = Steel or
   'C2' = Pure concrete
   'RC' or RC2 = Reinforced concrete (USE RC2, RC IS OUTDATED).
   'MC' or 'MMC' = (Modified) Mohr-Coulomb friction criteria
   material_name is the name used to refer to this material and can be
   choosen freely.
   materials.(material_name).physical_names = (cell) contains the
   physical names from the mesh which this material applies to.
   Depending on whether material is steel or reinforced concrete the
   struct will also have fields:
   S:  fY = yield strength [MPa]
   C2: k  = k - parameter in Mohr_Coulomb k*s1 - s3 = fc
       fc = concrete compressive strength [MPa];
       ft = concrete tensile strength [MPa];
   RC: k  = k - parameter in Mohr_Coulomb k*s1 - s3 = fc
   RC2 fc = concrete compressive strength [MPa];
       ft = concrete tensile strength [MPa];
       a = [Ax, Ay, Az] = reinforcement deegree in x, y or z-direction as
        the ratio [mm^2 reinforcement / mm^2 concrete]
       fY = [fYx, fYy, fYz] = reinforcement yield strength [MPa]
   MC: phi = Friction coefficient [Rad]
   MMC c   = Cohesion [MPa]
       ft = tension cutoff [MPa] for MC ft=inf (goverened by sliding failure;
  supports: struct: struct with the following build:
   supports.(physical_name) = (int), where int is either 1=x, 2=y, 3=z
  loads: struct: struct with the follwing build:
   loads.(type).(physical_name) = [fx, fy, fz], where fx, fy and fz are
   load in each principal direction.
   (type) is which type of load is defined which can be either point,
   line, surface or volume.
 Optional input:
  options: struct: Structure which contains different options to be used
  througout the program.
 Output:
  sol: struct: structure containing the solution with fields:
   xt: Total stresses in each stresspoint
   xs: Stresses in steel (for RC shows steek part if concrete
   xc: concrete stresses (without smeared reinforcement)
   y : collapse mode
   lambda: load-factor
  prob: struct: problem input matrices
   X: node coordinats matrix
   T: element topology matrix
   G: material parameters struct
   S: supports matrix
   L: load matrix
 Latest author:
 15-08-2019 Mads Emil Møller Andersen - MEMAndersen@gmail.com
CROSS-REFERENCE INFORMATION
This function calls:
setcon_cmm3 setcon_cmm3: Assembels the contraint matrix
seth_cmm3 seth_cmm: Assembles the global equilibrium matrix
setload_cmm3 setload_cmm: Creates the RHS of equilibrium constraint
setsup_cmm3 setsup_cmm: Excludes the supported dofs from the eq. matrix
setvareq_cmm3 setvareq_cmm: Sets variable equations and determines varous geometric
solveopt_cmm3 solveopt_cmm: Created the conic constraint matrices.
fela_load fela_load: Create load matrix
fela_material fela_material: Create material struct for program
fela_options general options
fela_support fela_support: Create supports matrix
fix_mesh fix_mesh: Makes input mesh ready to be used in mema_fela by changing
load_msh Open file and get lines
write_log write_log: Logging in cmw and to file
load_msh load_msh: Loads .msh mesh files from GMSH into the program
This function is called by:
SOURCE CODE
function [sol, prob]= fela_main(msh_path, materials, supports, loads, varargin)
% fela_main: Main runner of the FELA-program
%  FORMAT: res = fela_main(msh_path, material, supports, loads, varargin)
%
% Input:
%  msh_path: string: Path to mesh file, by default this is expected to be a
%   .msh file v. 4.1 created in GMSH
%
%  materials: struct: struct with the following build:
%   materials.(material_name).type = (str), where str is either:
%   'S' = Steel or
%   'C2' = Pure concrete
%   'RC' or RC2 = Reinforced concrete (USE RC2, RC IS OUTDATED).
%   'MC' or 'MMC' = (Modified) Mohr-Coulomb friction criteria
%   material_name is the name used to refer to this material and can be
%   choosen freely.
%   materials.(material_name).physical_names = (cell) contains the
%   physical names from the mesh which this material applies to.
%   Depending on whether material is steel or reinforced concrete the
%   struct will also have fields:
%
%   S:  fY = yield strength [MPa]
%
%   C2: k  = k - parameter in Mohr_Coulomb k*s1 - s3 = fc
%       fc = concrete compressive strength [MPa];
%       ft = concrete tensile strength [MPa];
%
%   RC: k  = k - parameter in Mohr_Coulomb k*s1 - s3 = fc
%   RC2 fc = concrete compressive strength [MPa];
%       ft = concrete tensile strength [MPa];
%       a = [Ax, Ay, Az] = reinforcement deegree in x, y or z-direction as
%        the ratio [mm^2 reinforcement / mm^2 concrete]
%       fY = [fYx, fYy, fYz] = reinforcement yield strength [MPa]
%
%   MC: phi = Friction coefficient [Rad]
%   MMC c   = Cohesion [MPa]
%       ft = tension cutoff [MPa] for MC ft=inf (goverened by sliding failure;
%
%  supports: struct: struct with the following build:
%   supports.(physical_name) = (int), where int is either 1=x, 2=y, 3=z
%
%  loads: struct: struct with the follwing build:
%   loads.(type).(physical_name) = [fx, fy, fz], where fx, fy and fz are
%   load in each principal direction.
%   (type) is which type of load is defined which can be either point,
%   line, surface or volume.
%
%
% Optional input:
%  options: struct: Structure which contains different options to be used
%  througout the program.
%
%
% Output:
%  sol: struct: structure containing the solution with fields:
%   xt: Total stresses in each stresspoint
%   xs: Stresses in steel (for RC shows steek part if concrete
%   xc: concrete stresses (without smeared reinforcement)
%   y : collapse mode
%   lambda: load-factor
%  prob: struct: problem input matrices
%   X: node coordinats matrix
%   T: element topology matrix
%   G: material parameters struct
%   S: supports matrix
%   L: load matrix
%
% Latest author:
% 15-08-2019 Mads Emil Møller Andersen - MEMAndersen@gmail.com
% Start timer
tic
write_log('\n\nStarting main program\n')
%% Input parser
% parse input
input = inputParser;
input.FunctionName = 'fela_main';
addRequired(input, 'msh_path', @isfile)
addRequired(input, 'materials', @isstruct)
addRequired(input, 'supports', @isstruct)
addRequired(input, 'loads', @isstruct)
addOptional(input, 'options', fela_options(), @isstruct)
parse(input, msh_path, materials, supports, loads, varargin{:})
%% Handle input
% Load .msh file and fix
mesh = load_msh(input.Results.msh_path);
mesh = fix_mesh(mesh);
% Unpack mesh and initlize prob struct
prob.T = mesh.domain.elements;
prob.X = mesh.nodes;
% Get nel and nno
nel = size(prob.T,1); mesh.nel = nel; prob.nel = nel;
nno = size(prob.X,1); mesh.nno = nno; prob.nno = nno;
% MATERIALs:
write_log('Creating material data array. Time %2.2f ',toc)
prob.G = fela_material(mesh, input.Results.materials);
% SUPPORTS:
write_log('Creating support data array. Time %2.2f ',toc)
prob.S = fela_support(mesh, input.Results.supports);
% LOADS:
write_log('Creating loads data array. Time %2.2f ',toc)
prob.L = fela_load(mesh, prob.X, input.Results.loads);
%% Create system matrices
write_log('Determining equation structure. Time %2.2f ',toc)
[nno,nel,nvar,neq,varperel,eqperel,~]=setvareq_cmm3(prob.X,prob.T);
% establish equilibrium matrix
write_log('Establishing equilibrium matrix. Time %2.2f ',toc)
H=seth_cmm3(prob.X,prob.T,nel,neq,nvar,eqperel,varperel);
% set supports
write_log('Setting supports. Time %2.2f ',toc)
[prob.supeq,H]=setsup_cmm3(prob.S,H);
% set loads
write_log('Setting loads. Time %2.2f ',toc)
[~,Rsup]=setload_cmm3(neq,prob.supeq,prob.L);
% set constraints
write_log('Setting constraints. Time %2.2f ',toc)
[Ab,blc,buc,bs,bt,subi] = setcon_cmm3(nel,prob.G,input.Results.options);
%% Optimize
write_log('Optimizing. Time %2.2f ',toc)
[sol]=solveopt_cmm3(nel,H,Rsup,Ab,blc,buc,bs,bt,subi,prob.G,input.Results.options);
write_log('Program over. Time %2.2f',toc)
write_log('lambda = %.2f', sol.lambda)
write_log('close')
end