Description of fela_post
fela_post
PURPOSE
fela_post: Post processing of solution, matlat plots or vtk files are
SYNOPSIS
function fela_post(sol, prob, varargin)
DESCRIPTION
 fela_post: Post processing of solution, matlat plots or vtk files are
 written
  FORMAT: fela_post(sol, varargin)
 Input:
  path: string: Path to write file
  prob: struct: Struct containing the problem, see fela_main for what it
   consists of.
  sol: struct: Struct containing the solution, see fela_main for what it
   consists of.
 Optional input:
  options: struct: Structure which contains different options to be used
  througout the program.
 Latest author:
 15-08-2019 Mads Emil Møller Andersen - MEMAndersen@gmail.com
CROSS-REFERENCE INFORMATION
This function calls:
plotDof_cmm3 plotDof_cmm3: Plots the principle stresses
plotPS_cmm3 plotPS_cmm3: Plots the principle stresses
fela_options general options
drawUCS Code by Henry Giddens on MATHWORKS
write_log write_log: Logging in cmw and to file
vtkwrite_tet vtkwrite_tet: Writes a .VTK file to visualize results in paraview.
distFig ===== Syntax ============================================================
This function is called by:
SOURCE CODE
function fela_post(sol, prob, varargin)
% fela_post: Post processing of solution, matlat plots or vtk files are
% written
%  FORMAT: fela_post(sol, varargin)
%
%
% Input:
%  path: string: Path to write file
%  prob: struct: Struct containing the problem, see fela_main for what it
%   consists of.
%  sol: struct: Struct containing the solution, see fela_main for what it
%   consists of.
%
%
% Optional input:
%  options: struct: Structure which contains different options to be used
%  througout the program.
%
% Latest author:
% 15-08-2019 Mads Emil Møller Andersen - MEMAndersen@gmail.com
% Start timer
tic
write_log('\n\nStarting post processing\n')
% parse input
input = inputParser;
input.FunctionName = 'fela_post';
addRequired(input, 'sol', @isstruct)
addRequired(input, 'prob', @isstruct)
addOptional(input, 'options', fela_options(), @isstruct)
parse(input, sol, prob, varargin{:})
sol = input.Results.sol;
prob = input.Results.prob;
% extract relevant options
op = input.Results.options.post;
%% Save problem and or solution
if op.save_prob || op.save_sol
    if ~exist(op.out_folder,'dir')
        mkdir(op.out_folder)
    end
    save_vars = {'prob', 'sol'};
    save_path = strcat(op.out_folder, filesep, op.save_name);
    save(save_path,save_vars{[op.save_prob, op.save_sol]})
end
%% Create .vtk file
if input.Results.options.post.create_vtk
    write_log('Writing .vtk visualizer file. Time %2.2f',toc)
    if ~exist(op.vtk_folder,'dir')
        mkdir(op.vtk_filename)
    end
    vtk_fname_f = strcat(op.vtk_fname_pre, op.vtk_fname, op.vtk_fname_suf,'.vtk');
    vtk_path = strcat(op.vtk_folder, filesep, vtk_fname_f);
    vtkwrite_tet(vtk_path, prob, sol);
end
%% Plot collapsemode
if input.Results.options.post.plot_collapse
    write_log('Plotting collapse mode. Time %2.2f ',toc)
    scale = op.plot_collapse_scale;
    plotDof_cmm3(prob.X,prob.T,sol.y,prob.supeq,prob.nel,prob.nno,scale,...
        'plotSurf',true,'axisTog',true)
    view(gca,[14.6 23]); drawUCS(gca,20)
    distFig()
end
%% Plot principle stresses
if input.Results.options.post.plot_principle
    % plot principal stress in element
    write_log('Plotting principal stresses. Time %2.2f ',toc)
    scale = op.plot_principle_scale;
    plotPS_cmm3(prob.X,prob.T,[sol.xt;sol.lambda],prob.nel, ...
        scale,'axisTog',true,'plotSurf',true);
    view(gca,[14.6 23]); drawUCS(gca,20)
    distFig()
end
write_log('Post processing ended. Time %2.2f',toc)
end