Description of write_log
write_log
PURPOSE
write_log: Logging in cmw and to file
SYNOPSIS
function write_log(data,varargin)
DESCRIPTION
 write_log: Logging in cmw and to file
  FORMAT: fela_init(msk_path,fela_path)
 Input:
  data: string: data to be written in log, can also be either 'open' which
   generates a new log file, or 'close' which executes the current logging
   session or one of the following which controls what is logged:
   'cw_logging'        cmw logging toogle
   'cw_logging_on'     cmw logging on
   'cw_logging_off'    cmw logging off
   'file_logging'      file logging toogle
   'file_logging_on'   file logging on
   'file_logging_off'  file logging off
  varagin: the 'data' string supports string formatting like a usual
   fpintf() or sprintf() function call
 29-07-2019 Mads Emil Møller Andersen - MEMAndersen@gmail.com
 Losely adapted after code by Jan on the MATHWORKS forums
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
fela_init fela_init: Initialize mosek and set various settings related to logging
fela_main fela_main: Main runner of the FELA-program
fela_post fela_post: Post processing of solution, matlat plots or vtk files are
abaqus2matlab
abaqus2matlab
SOURCE CODE
function write_log(data,varargin)
% write_log: Logging in cmw and to file
%  FORMAT: fela_init(msk_path,fela_path)
% Input:
%  data: string: data to be written in log, can also be either 'open' which
%   generates a new log file, or 'close' which executes the current logging
%   session or one of the following which controls what is logged:
%   'cw_logging'        cmw logging toogle
%   'cw_logging_on'     cmw logging on
%   'cw_logging_off'    cmw logging off
%   'file_logging'      file logging toogle
%   'file_logging_on'   file logging on
%   'file_logging_off'  file logging off
%  varagin: the 'data' string supports string formatting like a usual
%   fpintf() or sprintf() function call
%
% 29-07-2019 Mads Emil Møller Andersen - MEMAndersen@gmail.com
% Losely adapted after code by Jan on the MATHWORKS forums
% File ID persistent
persistent FID
persistent file_logging
persistent cw_logging
% Open the logging file
if strcmp(data, 'open')
    log_name = strcat('MATLAB_log_', datestr(now,'yyyy-mm-dd-HH-MM-SS'),'.txt');
    FID = fopen(fullfile(tempdir, log_name), 'w');
    if FID < 0
        error('Cannot open file');
    end
    return;
    % Close logging file
elseif strcmp(data, 'close')
    fclose(FID);
    FID = -1;
    return
end
% control logging to log file
if isempty(file_logging) || strcmp(data, 'file_logging_on')
    file_logging = true;
    return
elseif strcmp(data, 'file_logging_off')
    file_logging = false;
    return
elseif strcmp(data, 'file_logging')
    file_logging = ~file_logging;
    return
end
% control logging to command window
if isempty(cw_logging) || strcmp(data, 'cw_logging_on')
    cw_logging = true;
    return
elseif strcmp(data, 'cw_logging_off')
    cw_logging = false;
    return
elseif strcmp(data, 'cw_logging')
    cw_logging = ~cw_logging;
    return
end
% write to log
if file_logging
    fprintf(FID, strcat(datestr(now,'yyyy-mm-dd-HH-MM-SS'),': ', data,'\n'),varargin{:});
end
% Write to the screen at the same time:
if cw_logging
    fprintf(strcat(data,'\n'),varargin{:});
end